### ISSUE TITLE
[Debian 12] start server... in log, then nothing happens.

### ISSUE THREAD

**Issue by SSUPII** [barry-ran/QtScrcpy#1033]
This issue is not present in the Windows build of QtScrcpy.

Clicking "start server" on the only device present on the list will print "start server..." in the log, then nothing happens. Nothing else is printed.

Errors are printed in the system logs (main folders paths have been dotted for privacy):
```
"./adb" "-s d5c512f1 push ./scrcpy-server /data/local/tmp/scrcpy-server.jar"
AdbProcessImpl::out:./scrcpy-server: 1 file pushed, 0 skipped. 179.1 MB/s (69007 bytes in 0.000s)
"./adb" "-s d5c512f1 reverse localabstract:scrcpy_00001122 tcp:27183"
adb return  0 exit status  QProcess::NormalExit
"./adb" "-s d5c512f1 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 2.1.1 video_bit_rate=2000000 log_level=info max_size=1080 audio=false scid=00001122"
adb return  0 exit status  QProcess::NormalExit
"./adb" "-s d5c512f1 reverse --remove localabstract:scrcpy_00001122"
qprocess start error:./adb -s d5c512f1 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 2.1.1 video_bit_rate=2000000 log_level=info max_size=1080 audio=false scid=00001122
adb return  9 exit status  QProcess::CrashExit
```

Clicking "start audio" works without issues, but of course no server means no screen view.

Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-23-amd64 (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: VivoBook_ASUSLaptop X580GD_N580GD
System Version: 1.0

**Comment by SSUPII** [comment]
Just noticed that disabling Reverse Connection shows this error:

```
video socket connect to server read device info failed, try again

AdbProcessImpl::error:[server] ERROR: The server version (2.4) does not match the client (2.1.1)
java.lang.IllegalArgumentException: The server version (2.4) does not match the client (2.1.1)
	at com.genymobile.scrcpy.Options.parse(Options.java:237)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:231)
	at com.genymobile.scrcpy.Server.main(Server.java:214)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
```

**Comment by llc0930** [comment]
If you just want to use it... I've already reported this issue...
https://github.com/barry-ran/QtScrcpy/issues/1026#issue-2474645621
