### ISSUE TITLE
can't start server 

### ISSUE THREAD

**Issue by trialman** [barry-ran/QtScrcpy#1039]
AdbProcessImpl::error:[server] ERROR: The server version (2.4) does not match the client (1.24)
java.lang.IllegalArgumentException: The server version (2.4) does not match the client (1.24)
	at com.genymobile.scrcpy.Options.parse(Options.java:237)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:231)
	at com.genymobile.scrcpy.Server.main(Server.java:214)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:374)

**Comment by flyingicedragon** [comment]
Maybe need change `scrcpy-server`
#1026
