### ISSUE TITLE
小米14不能控制屏幕，能看到

### ISSUE THREAD

**Issue by vltown** [barry-ran/QtScrcpy#1047]
"pos": {"x": 0.458221, "y": 0.443499}

AdbProcessImpl::error:[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)

AdbProcessImpl::error:at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:362)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:162)
	at com.genymobile.scrcpy.Controller.control(Controller.java:97)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1575)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:911)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:744)
	at android.os.Binder.execTransactInternal(Binder.java:1346)
	at android.os.Binder.execTransact(Binder.java:1282)

AdbProcessImpl::error:[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)

AdbProcessImpl::error:at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:234)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:362)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:162)
	at com.genymobile.scrcpy.Controller.control(Controller.java:97)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1575)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
	... 10 more

update devices...
adb run
AdbProcessImpl::out:List of devices attached
bb8056e6	device

update devices...
adb run
AdbProcessImpl::out:List of devices attached
bb8056e6	device

update devices...
adb run
AdbProcessImpl::out:List of devices attached
bb8056e6	device

update devices...
adb run
AdbProcessImpl::out:List of devices attached
bb8056e6	device

**Comment by vltown** [comment]
USB调试和USB调试（安全设置）都打开了

**Comment by creeperwater** [comment]
Mi has pushed a system update which can fix this problem.

**Comment by xfause** [comment]
HyperOS 2.0.11.0
QtScrcpy 3.0.1
still have same issue.

**Comment by Snowarden** [comment]
1楼正解，小米的系统有两个USB调试选项，在USB调试选项下面还有个USB调试（安全设置）的选项，这个打开电脑才有权限控制点击和触摸。
