### ISSUE TITLE
still on 2.1.1

### ISSUE THREAD

**Issue by end3r-man** [barry-ran/QtScrcpy#1078]
```log
AdbProcessImpl::error:[server] ERROR: The server version (3.0.2) does not match the client (2.1.1)
java.lang.IllegalArgumentException: The server version (3.0.2) does not match the client (2.1.1)
	at com.genymobile.scrcpy.Options.parse(Options.java:288)
	at com.genymobile.scrcpy.Server.internalMain(Server.java:218)


AdbProcessImpl::error:at com.genymobile.scrcpy.Server.main(Server.java:201)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by end3r-man** [comment]
im using the latest version

**Comment by barry-ran** [comment]
update config.ini
