### ISSUE TITLE
截图功能,分辨率有问题

### ISSUE THREAD

**Issue by xuezh01** [barry-ran/QtScrcpy#112]
我手机分辨率是1080x2340,用截图功能的时候,尺寸受最大尺寸限制,只能截到相应分辨率的图
如果用原始选项,无法启动投屏功能,荣耀9x

测试雷电模拟器540x960分辨率,用原始选项截出来的图是
744x1328

两个都有问题

**Comment by barry-ran** [comment]
荣耀9x 原始选项投屏报什么错误？

**Comment by xuezh01** [comment]
> 荣耀9x 原始选项投屏报什么错误？

getScreenRect is empty

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:167)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:68)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
[server] ERROR: The hardware encoder is not able to encode at the given definition.
[server] ERROR: Try with a lower definition:
[server] ERROR:     scrcpy -m 1024
Exit due to uncaughtException in main thread:
