### ISSUE TITLE
MI 8 运行一段时间后报错 FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)

### ISSUE THREAD

**Issue by fairytale110** [barry-ran/QtScrcpy#149]
环境：
Win10 x64 i7八代笔记本
小米8：MIUI11.0.4稳定版 PEACNXM
已root
Android 9
运行一段时间后，屏幕常亮，然后掉线，需要重新拔插数据线才能再搜索到设备。
错误日志：
```java
start server...
getScreenRect is empty

AdbProcess::out:F:/QtScrcpy-win-x64-v1.3.2/QtScrcpy-win-x64-v1.3.2/scrcpy-server: 1 file pushed. 0.9 MB/s (26142 bytes in 0.027s)

server start finish in 0.641s

getScreenRect is empty

AdbProcess::error:java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
	at android.content.res.Resources.<init>(Resources.java:267)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:190)
	at android.app.LoadedApk.<init>(LoadedApk.java:211)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

AdbProcess::out:

update devices...
adb run
AdbProcess::out:List of devices attached
b1f72cfa	device

start server...
getScreenRect is empty

AdbProcess::out:F:/QtScrcpy-win-x64-v1.3.2/QtScrcpy-win-x64-v1.3.2/scrcpy-server: 1 file pushed. 2.9 MB/s (26142 bytes in 0.008s)

server start finish in 0.861s

getScreenRect is empty

AdbProcess::error:java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:40)
	at android.content.res.Resources.<init>(Resources.java:267)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:190)
	at android.app.LoadedApk.<init>(LoadedApk.java:211)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2331)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:388)

AdbProcess::out:[server] WARN: Max FPS is only supported since Android 10, the option has been ignored

```

**Comment by yyconstantine** [comment]
环境：
米9 Android10，启动服务后出现类似报错
MacOS 10.14.6
release-1.3.3
日志：
adb run
start server...
getScreenRect is empty

AdbProcess::out:/Applications/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed. 2.8 MB/s (26142 bytes in 0.009s)

server start finish in 0.315s

AdbProcess::error:java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
	at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
	at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
	at android.content.res.Resources.<init>(Resources.java:283)
	at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
	at android.content.res.Resources.getSystem(Resources.java:204)
	at android.app.LoadedApk.<init>(LoadedApk.java:235)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2430)
	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2427)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.Workarounds.fillAppInfo(Workarounds.java:66)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:56)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 22 more

**Comment by fairytale110** [comment]
好像不影响使用了
