### ISSUE TITLE
scrcpy版本与client不配对 （Linux）

### ISSUE THREAD

**Issue by TheInterestingSoul** [barry-ran/QtScrcpy#235]
本人arch linux，今天从码云上克隆了一份（1.14），用qt creator构建后，测试正常：
```
adb run
start server...
AdbProcess::out:../../../third_party/scrcpy-server: 1 file pushed. 4.1 MB/s (33142 bytes in 0.008s)

AdbProcess::out:[server] INFO: Device: HUAWEI VTR-AL00 (Android 8.0.0)

AdbProcess::out:

server start finish in 1.568s
```
于是我想把scrcpy安装到/opt目录，结果将scrcpy-server和客户端复制到/opt后，竟然提示版本不配对，与 #222 如出一辙
```
start server...
AdbProcess::out:/opt/QtScrcpy/scrcpy-server: 1 file pushed. 4.8 MB/s (44671 bytes in 0.009s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::out:

AdbProcess::error:java.lang.IllegalArgumentException: The server version (1.14) does not match the client (1.12.1)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:315)
Exit due to uncaughtException in main thread:
```
好像是那个config.ini没整对，但是我把它复制过来后，仍然没有效果
修改客户端版本号重新编译、修改server版本号编译、切换到dev分支，都没有效果
- - - 
补充：阅读源码后，发现读取config是有一个环境变量的，但是
```bash
export QTSCRCPY_CONFIG_PATH="/opt/QtScrcpy/config"
```
也没有效果

**Comment by barry-ran** [comment]
你的scrcpy-server搞错了，使用了旧版本的scrcpy-server，你可以用[这个](https://raw.githubusercontent.com/barry-ran/QtScrcpy/master/third_party/scrcpy-server)试试
