### ISSUE TITLE
请求增加自定义adb path的功能

### ISSUE THREAD

**Issue by fgheng** [barry-ran/QtScrcpy#255]
我不知道为什么总是提示adbserver的版本跟client的不一致，是因为qtscrcpy自带了adb么？可不可以自定义使用adb的路径呢？

**Comment by eMUQI** [comment]
AdbProcess::out:

AdbProcess::error:java.lang.IllegalArgumentException: The server version (1.14) does not match the client (1.12.1)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:362)

**Comment by eMUQI** [comment]
感觉是scrcpy的版本问题，能否自定义scrcpy path呢

**Comment by barry-ran** [comment]
config.ini里早就可以自定义了
