### ISSUE TITLE
Don't hardcode scrcpy server version

### ISSUE THREAD

**Issue by yochananmarqos** [barry-ran/QtScrcpy#267]
Now that `scrcpy` 1.15 is out, QtScrpy is broken again due to looking for 1.14:

```
""
"QtScrcpy"
This software is completely open source and free. Strictly used for illegal purposes, or at your own risk. You can download it at the following address:
"QtScrcpy  <https://github.com/barry-ran/QtScrcpy>"
adb path: /usr/bin/adb
"/usr/bin/adb" "connect 192.168.8.114:5555"
AdbProcess::out:already connected to 192.168.8.114:5555
adb return  0 exit status  QProcess::NormalExit
"/usr/bin/adb" "devices"
AdbProcess::out:List of devices attached
192.168.8.114:5555	device
adb return  0 exit status  QProcess::NormalExit
"/usr/bin/adb" "-s 192.168.8.114:5555 push /usr/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar"
AdbProcess::out:/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 243.6 MB/s (33618 bytes in 0.000s)
"/usr/bin/adb" "-s 192.168.8.114:5555 reverse localabstract:scrcpy tcp:27183"
adb return  0 exit status  QProcess::NormalExit
"/usr/bin/adb" "-s 192.168.8.114:5555 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.14 info 1080 8000000 60 -1 false - true true 0 false false -"
adb return  0 exit status  QProcess::NormalExit
AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]
AdbProcess::error:java.lang.IllegalArgumentException: The server version (1.15) does not match the client (1.14)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:119)
	at com.genymobile.scrcpy.Server.main(Server.java:221)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:362)
server process stop
adb return  0 exit status  QProcess::NormalExit
"/usr/bin/adb" "-s 192.168.8.114:5555 reverse --remove localabstract:scrcpy"
adb return  0 exit status  QProcess::NormalExit
```

**Comment by Leon406** [comment]
temp solution:
downgrade scrcpy-server.exe to previous version,and  it works fine for me

**Comment by barry-ran** [comment]
What happened? Do not mix qtscrcpy and scrcpy servers

**Comment by yochananmarqos** [comment]
@barry-ran 
What do you mean, what happened?
