### ISSUE TITLE
刷新设备之后，点击启动服务电脑上投射的手机屏幕闪退

### ISSUE THREAD

**Issue by liguang-ops** [barry-ran/QtScrcpy#275]
adb run
AdbProcess::out:List of devices attached
SJE5T17B17000109	device

start server...
AdbProcess::out:D:/Program Files/QtScrcpy-win-x64-v1.4.0/scrcpy-server: 1 file pushed. 0.9 MB/s (33142 bytes in 0.037s)

AdbProcess::out:[server] INFO: Device: HUAWEI VTR-AL00 (Android 9)

server start finish in 0.77s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

**Comment by barry-ran** [comment]
修改分辨率

**Comment by liguang-ops** [comment]
尝试修改了手机分辨率（华为p10），仍旧报同样的错误。
start server...
AdbProcess::out:D:/Program Files/QtScrcpy-win-x64-v1.4.0/scrcpy-server: 1 file pushed. 0.4 MB/s (33142 bytes in 0.075s)

AdbProcess::out:[server] INFO: Device: HUAWEI VTR-AL00 (Android 9)

server start finish in 0.81s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:205)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:84)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:
