### ISSUE TITLE
魅族16th plus

### ISSUE THREAD

**Issue by lovesunyiyi** [barry-ran/QtScrcpy#33]
start server...
libpng warning: iCCP: known incorrect sRGB profile

AdbProcess::out:[100%] /data/local/tmp/scrcpy-server.jar

AdbProcess::out:C:/Users/Sun/Desktop/QtScrcpy-win64-v1.0.3/scrcpy-server.jar: 1 file pushed. 2.0 MB/s (23362 bytes in 0.011s)

server start finish in 0.985s

Could not open video stream

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at android.media.MediaCodec.configure(MediaCodec.java:1918)
	at android.media.MediaCodec.configure(MediaCodec.java:1873)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:33)
	at com.genymobile.scrcpy.Server.main(Server.java:134)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by barry-ran** [comment]
魅族手机确实有这个问题，处理中。。。

**Comment by hezlog** [comment]
我也遇到了 魅族 16X


start server...
update devices...
adb run
AdbProcess::out:List of devices attached
872QAET9Y3E2U	device

update devices...
adb run
AdbProcess::out:List of devices attached
872QAET9Y3E2U	device

start server...
libpng warning: iCCP: known incorrect sRGB profile

AdbProcess::out:[100%] /data/local/tmp/scrcpy-server.jar

AdbProcess::out:D:/downloads/Mobile/QtScrcpy-win64-v1.0.3/scrcpy-server.jar: 1 file pushed. 1.4 MB/s (23362 bytes in 0.016s)

server start finish in 1.651s

Could not open video stream

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at android.media.MediaCodec.configure(MediaCodec.java:1918)
	at android.media.MediaCodec.configure(MediaCodec.java:1873)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:158)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:33)
	at com.genymobile.scrcpy.Server.main(Server.java:134)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by barry-ran** [comment]
v1.1.0已经修复
