### ISSUE TITLE
大神们，我的启动不成功！

### ISSUE THREAD

**Issue by CIHOO2020** [barry-ran/QtScrcpy#388]
start server...
AdbProcess::out:C:/QtS/scrcpy-server: 1 file pushed, 0 skipped. 19.5 MB/s (34930 bytes in 0.002s)

AdbProcess::out:[server] INFO: Device: Amlogic H96 Max X3 (Android 9)

server start finish in 1.338s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:113)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:94)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

**Comment by CIHOO2020** [comment]
我是菜鸟 我不懂JAVA!

**Comment by Lonely-Leisure** [comment]
![image](https://user-images.githubusercontent.com/61188191/124831089-5a2a7400-dfad-11eb-995f-2409822e8e69.png)
把上面这个选项的数值调低一些
