### ISSUE TITLE
连接pixel 3安卓12系统时候无法连接并闪退

### ISSUE THREAD

**Issue by xk7828** [barry-ran/QtScrcpy#519]
start server...
AdbProcess::out:G:/pixel/QtScrcpy-win-x64-v1.7.1/scrcpy-server: 1 file pushed, 0 skipped. 50.4 MB/s (34930 bytes in 0.001s)

AdbProcess::out:[server] INFO: Device: Google Pixel 3 (Android 12)

AdbProcess::out:[server] ERROR: Could not invoke method

AdbProcess::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:83)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getValue(ContentProvider.java:124)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:140)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)

AdbProcess::error:at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:119)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.content.ContentProvider.validateIncomingAuthority(ContentProvider.java:2521)
	at android.content.ContentProvider.access$300(ContentProvider.java:109)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:506)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
	at android.os.Binder.execTransactInternal(Binder.java:1179)

AdbProcess::out:[server] ERROR: Could not invoke method

AdbProcess::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ContentProvider.call(ContentProvider.java:83)
	at com.genymobile.scrcpy.wrappers.ContentProvider.putValue(ContentProvider.java:136)
	at com.genymobile.scrcpy.wrappers.ContentProvider.getAndPutValue(ContentProvider.java:142)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:39)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.SecurityException: The authority unknown does not match the one of the contentProvider: settings
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
	at android.content.IContentProvider.call(IContentProvider.java:119)
	... 8 more

server start finish in 0.534s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3145)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2214)
	... 9 more

**Comment by along12llmkj** [comment]
adb devices
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

update devices...
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 78.8 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::out:

AdbProcess::error:java.lang.NumberFormatException: For input string: "2690588000"
	at java.lang.Integer.parseInt(Integer.java:618)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:183)
	at com.genymobile.scrcpy.Server.main(Server.java:305)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 92.8 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::out:

AdbProcess::error:java.lang.NumberFormatException: For input string: "2690588000"
	at java.lang.Integer.parseInt(Integer.java:618)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:183)
	at com.genymobile.scrcpy.Server.main(Server.java:305)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 90.3 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

AdbProcess::out:

server start finish in 0.831s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 81.4 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

AdbProcess::out:

server start finish in 0.834s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
start server...
AdbProcess::error:adb F 01-27 14:44:41 24460 24740 file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 89.1 MB/s (40067 bytes in 0.000s)

adb push failed

qprocess start error:D:/QtScrcpy-win-x64-v1.8.1/adb -s emulator-5554 push D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server /data/local/tmp/scrcpy-server.jar

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

AdbProcess::out:

server start finish in 0.837s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 76.1 MB/s (40067 bytes in 0.001s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

server start finish in 0.775s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 93.2 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

server start finish in 0.768s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::error:adb F 01-27 14:44:56 10440 25824 file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254

start server...
adb push failed

qprocess start error:D:/QtScrcpy-win-x64-v1.8.1/adb -s emulator-5554 push D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server /data/local/tmp/scrcpy-server.jar

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 93.4 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

AdbProcess::out:

server start finish in 0.802s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

update devices...
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

update devices...
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

update devices...
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

update devices...
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

get ip...
adb run
AdbProcess::out:wlan0     Link encap:UNSPEC  
          inet addr:192.168.3.125  Bcast:192.168.3.255  Mask:255.255.255.0 
          inet6 addr: fe80::1eb7:96ff:fe22:b34d/64 Scope: Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:786742 errors:0

AdbProcess::out:dropped:36 overruns:0 frame:0 
          TX packets:459665 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:665512238 TX bytes:145516625

start devices adbd...
adb run
AdbProcess::out:restarting in TCP mode port: 5555

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 69.2 MB/s (40067 bytes in 0.001s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

server start finish in 0.85s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 87.9 MB/s (40067 bytes in 0.000s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

AdbProcess::out:

server start finish in 0.788s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 67.1 MB/s (40067 bytes in 0.001s)

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

AdbProcess::out:

server start finish in 0.805s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:

update devices...
adb run
AdbProcess::out:List of devices attached
79UDU19823020457	device
192.168.137.86:5555	offline
emulator-5554	device

start server...
AdbProcess::error:adb F 01-27 14:45:53  7840 13104 file_sync_client.cpp:503] protocol fault: stat response has wrong message id: 1279869254

start server...
AdbProcess::out:D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server: 1 file pushed, 0 skipped. 90.7 MB/s (40067 bytes in 0.000s)

adb push failed

qprocess start error:D:/QtScrcpy-win-x64-v1.8.1/adb -s emulator-5554 push D:/QtScrcpy-win-x64-v1.8.1/scrcpy-server /data/local/tmp/scrcpy-server.jar

AdbProcess::out:[server] INFO: Device: HUAWEI HRY-LX1 (Android 9)

server start finish in 0.817s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1967)
	at android.media.MediaCodec.configure(MediaCodec.java:1896)
	at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:233)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:
