### ISSUE TITLE
Google Pixel 4 XL (Android 12) error

### ISSUE THREAD

**Issue by Dtrieb** [barry-ran/QtScrcpy#521]
AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3145)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2214)
	... 9 more

**Comment by cheetah747** [comment]
I have the same problem as you. I am android 12 too

**Comment by RaptorX** [comment]
This seems to be the same issue as #705
