### ISSUE TITLE
Mix4 安卓12运行报错，闪一下然后出现以下代码

### ISSUE THREAD

**Issue by sanchixuan** [barry-ran/QtScrcpy#528]
start server...
AdbProcess::out:E:/QtScrcpy/scrcpy-server: 1 file pushed, 0 skipped. 0.6 MB/s (34930 bytes in 0.056s)

AdbProcess::out:[server] INFO: Device: Xiaomi 2106118C (Android 12)

server start finish in 1.384s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:243)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:60)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:80)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3232)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2251)
	... 9 more

**Comment by Runxsi** [comment]
macos 同 mix4 Android12 一样闪退报错

**Comment by kirer** [comment]
小米11U   miui13  安卓12 也不行。什么时候能适配下呢

**Comment by maru7777** [comment]
单独用scrcpy是可以操作安卓12的 只要把新的scrcpy整合进去就好了
