### ISSUE TITLE
安卓12/MIUI13 启动服务异常

### ISSUE THREAD

**Issue by gclm** [barry-ran/QtScrcpy#548]
## 启动日志
```
start server...
AdbProcess::out:/Applications/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed, 0 skipped. 67.7 MB/s (40067 bytes in 0.001s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException: '=' expected

AdbProcess::error:at com.genymobile.scrcpy.CodecOption.parseOption(CodecOption.java:72)
	at com.genymobile.scrcpy.CodecOption.parse(CodecOption.java:63)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:223)
	at com.genymobile.scrcpy.Server.main(Server.java:305)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)

```

**Comment by barry-ran** [comment]
你修改了Config.ini中的CodecOptions才出问题的吗？

**Comment by barry-ran** [comment]
还是默认就有问题？

**Comment by 378978764** [comment]
> 

默认就有问题，1.8.0 版本，MIUI 8 也不行。

**Comment by gclm** [comment]
@barry-ran  默认就没有问题

**Comment by 346673164** [comment]
我也有这种情况。华为鸿蒙

**Comment by Maddaxman** [comment]
相同情况，oppo coloros12

**Comment by xicong** [comment]
我也是这个错误  vivo iqoo8   之前旧版本用华为p30正常的 用 iqoo8 不行然后我就更新到了这个最新版结果两个手机都不行了

**Comment by xluu233** [comment]
更新[v1.8](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.8.1)

**Comment by gclm** [comment]
可以正常投屏了，但是无法操作投屏的手机
