### ISSUE TITLE
1.80 Android11(MIUI12.5) 息屏问题

### ISSUE THREAD

**Issue by Zhou9411** [barry-ran/QtScrcpy#549]
- 1.80无论是手动点击息屏还是勾选上息屏后再启动服务,均无法息屏,还会导致软件无法控制手机(点击软件命令窗口上会有显示坐标,但手机无反应).在1.71上无此问题.

> update devices...
"本软件完全开源免费，作者不对使用该软件产生的一切后果负责。你可以在以下地址下载："
"QtScrcpy 1.8.0 <https://github.com/barry-ran/QtScrcpy>"
AdbProcess::out:List of devices attached
d64ae247	device
update devices...
adb run
AdbProcess::out:List of devices attached
d64ae247	device
start server...
AdbProcess::out:D:/QtScrcpy/scrcpy-server: 1 file pushed, 0 skipped. 76.8 MB/s (40067 bytes in 0.000s)
AdbProcess::out:[server] INFO: Device: Xiaomi Redmi K30 Pro (Android 11)
AdbProcess::out:
server start finish in 0.337s
update devices...
adb run
AdbProcess::out:List of devices attached
d64ae247	device
start server...
AdbProcess::out:D:/QtScrcpy/scrcpy-server: 1 file pushed, 0 skipped. 73.7 MB/s (40067 bytes in 0.001s)
AdbProcess::out:[server] INFO: Device: Xiaomi Redmi K30 Pro (Android 11)
server start finish in 0.271s
"pos": {"x": 0.404167, "y": 0.475638}
AdbProcess::out:[server] ERROR: Exception on thread Thread[Thread-2,5,main]
AdbProcess::out:
AdbProcess::error:java.lang.IllegalArgumentException: Bad position -65522/30
	at java.nio.Buffer.position(Buffer.java:259)
	at java.nio.ByteBuffer.position(ByteBuffer.java:812)
	at com.genymobile.scrcpy.ControlMessageReader.parseString(ControlMessageReader.java:123)
	at com.genymobile.scrcpy.ControlMessageReader.parseSetClipboard(ControlMessageReader.java:182)
	at com.genymobile.scrcpy.ControlMessageReader.next(ControlMessageReader.java:78)
	at com.genymobile.scrcpy.DesktopConnection.receiveControlMessage(DesktopConnection.java:110)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:82)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$3.run(Server.java:125)
AdbProcess::error:at java.lang.Thread.run(Thread.java:923)
"pos": {"x": 0.4125, "y": 0.445476}
"pos": {"x": 0.592708, "y": 0.424594}

- 据群友反应1.7x版本和平精英会出现鼠标视角无法右转问题(即右转一小段距离后会被强制回拉到初始视角方位,小眼睛也会有此问题),我当时使用1.71无法复现此问题,直到启用QtScrcpy内置的录屏功能后,使用小眼睛出现上述问题,即使取消勾选录屏,删除1.71,再解压使用1.80依然存在上述问题(即不需要开启软件录屏功能,只要在和平精英内使用小眼睛右转视角,100%复现右转视角强制重置为初始视角问题)

**Comment by neurodiverseEsoteric** [comment]
I'm having the same issue

**Comment by a1239905826** [comment]
可以提供咱们关于QtScrcpy的交流群吗？？

**Comment by barry-ran** [comment]
try [v1.8.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.8.1)

**Comment by Zhou9411** [comment]
> 
1.8.1已初步测试:
1. 息屏功能正常
2. 和平精英游戏内小眼睛右转被强制回拉问题依然存在
