### ISSUE TITLE
the last version can't run on my android 12 phone(oppo find x3 pro)

### ISSUE THREAD

**Issue by Maddaxman** [barry-ran/QtScrcpy#553]
reported error:

AdbProcess::error:at com.genymobile.scrcpy.CodecOption.parseOption(CodecOption.java:72)
	at com.genymobile.scrcpy.CodecOption.parse(CodecOption.java:63)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:223)
	at com.genymobile.scrcpy.Server.main(Server.java:305)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)

**Comment by xtremforce** [comment]
same issue here

**Comment by Dtrieb** [comment]
me, too ([here](https://github.com/barry-ran/QtScrcpy/issues/521))

**Comment by RaptorX** [comment]
same issue here: #705
