### ISSUE TITLE
请问，遇到这种问题该如何解决

### ISSUE THREAD

**Issue by Pupper0601** [barry-ran/QtScrcpy#555]
update devices...
"本软件完全开源免费，作者不对使用该软件产生的一切后果负责。你可以在以下地址下载："

"QtScrcpy 1.8.0 <https://github.com/barry-ran/QtScrcpy>"

adb run
AdbProcess::out:List of devices attached
R58M86BEW0D	device

update devices...
adb run
AdbProcess::out:List of devices attached
R58M86BEW0D	device

start server...
AdbProcess::out:/Applications/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed, 0 skipped. 25.5 MB/s (40067 bytes in 0.002s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException: '=' expected
	at com.genymobile.scrcpy.CodecOption.parseOption(CodecOption.java:72)
	at com.genymobile.scrcpy.CodecOption.parse(CodecOption.java:63)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:223)
	at com.genymobile.scrcpy.Server.main(Server.java:305)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:409)

**Comment by longxiying** [comment]
+1

**Comment by uirozwang** [comment]
同樣遇到，回到上一版目前正常使用

**Comment by barry-ran** [comment]
try [v1.8.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.8.1)
