### ISSUE TITLE
小米电视无法使用

### ISSUE THREAD

**Issue by zhangjingex** [barry-ran/QtScrcpy#558]
尺寸设置低一点，比如720能成功连接，但是就显示一角，尺寸选大一点或者原始直接闪退

```
AdbProcess::out:[server] INFO: Device: xiaomi MiTV-MFTP0 (Android 9)

server start finish in 0.719s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:110)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:91)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:65)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:93)
	at com.genymobile.scrcpy.Server.main(Server.java:309)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
```

**Comment by beibei2a** [comment]
小米电视能开无限调试吗

**Comment by zhangjingex** [comment]
> 小米电视能开无限调试吗

能啊
