### ISSUE TITLE
mac bigsur启动时错误

### ISSUE THREAD

**Issue by Rainforestwind** [barry-ran/QtScrcpy#560]
start server...
AdbProcess::out:/Applications/QtScrcpy.app/Contents/MacOS/scrcpy-server: 1 file pushed, 0 skipped. 39.7 MB/s (40067 bytes in 0.001s)

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.IllegalArgumentException: '=' expected
	at com.genymobile.scrcpy.CodecOption.parseOption(CodecOption.java:72)
	at com.genymobile.scrcpy.CodecOption.parse(CodecOption.java:63)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:223)
	at com.genymobile.scrcpy.Server.main(Server.java:305)

AdbProcess::out:

AdbProcess::error:at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:438)

**Comment by thomasrebele** [comment]
As a Q&D workaround I changed the following lines in `QtScrcpy/util/config.cpp`
```
#define COMMON_CODEC_OPTIONS_KEY "CodecOptions"
#define COMMON_CODEC_OPTIONS_DEF ""

#define COMMON_CODEC_NAME_KEY "CodecName"
#define COMMON_CODEC_NAME_DEF "OMX.qcom.video.encoder.avc"
```

**Comment by barry-ran** [comment]
try [v1.8.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v1.8.1)
