### ISSUE TITLE
一加9pro无法连接

### ISSUE THREAD

**Issue by ciciyang1997** [barry-ran/QtScrcpy#563]
AdbProcess::out:List of devices attached
a0fec54d	device

libpng warning: iCCP: known incorrect sRGB profile

start server...
AdbProcess::out:[100%] /data/local/tmp/scrcpy-server.jar

AdbProcess::out:D:/妗岄潰/QtScrcpy/scrcpy-server.jar: 1 file pushed. 5.9 MB/s (49375 bytes in 0.008s)

server start finish in 1.121s

AdbProcess::out:DEBUG: Event controller stopped
ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:62)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:169)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:28)
	at com.genymobile.scrcpy.Server.main(Server.java:110)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:60)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3194)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2227)
	... 8 more

Could not open video stream

**Comment by hick** [comment]
the same phone with almost the same problem:  我也是一加9 pro 基本类似的问题

```
"QtScrcpy 1.4.3 <https://github.com/barry-ran/QtScrcpy>"

update devices...
adb path: D:/program/QtScrcpy-win-x86-v1.4.3/adb

adb run
AdbProcess::error:adb server version (31) doesn't match this client (41); killing...

wait for the end of the current command to run

AdbProcess::error:* daemon started successfully

AdbProcess::out:List of devices attached
c5d52cf6	device

start server...
AdbProcess::out:D:/program/QtScrcpy-win-x86-v1.4.3/scrcpy-server: 1 file pushed. 1.5 MB/s (33142 bytes in 0.021s)

AdbProcess::out:[server] INFO: Device: OnePlus LE2120 (Android 12)

server start finish in 0.417s

AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:216)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:86)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:55)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:76)
	at com.genymobile.scrcpy.Server.main(Server.java:225)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 7 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3299)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2275)
	... 9 more
```

**Comment by hick** [comment]
具体原因我不清楚,  不过我换了裸板的 scrcpy 没问题,  估计是新版本适配需要最新的 scrcpy 才行

**Comment by hick** [comment]
> 具体原因我不清楚, 不过我换了裸版的 scrcpy 没问题, 估计是新版本适配需要最新的 scrcpy 才行

进一步确认最新的 qtscrcpy 也没问题了哈
