### ISSUE TITLE
1.81息屏还是无法操作

### ISSUE THREAD

**Issue by asd0925** [barry-ran/QtScrcpy#567]
手上一台华为M6（系统版本安卓10）
一台oppo ace2（系统版本安卓11）
一台小米12（系统版本安卓12）
以上三台设备1.80和1.81版本息屏均无法操作，不息屏一切正常

华为M6（系统版本安卓10） 报错
AdbProcess::error:java.lang.IllegalArgumentException: Bad position -65522/58
	at java.nio.Buffer.position(Buffer.java:259)
	at java.nio.ByteBuffer.position(ByteBuffer.java:812)
	at com.genymobile.scrcpy.ControlMessageReader.parseString(ControlMessageReader.java:123)
	at com.genymobile.scrcpy.ControlMessageReader.parseSetClipboard(ControlMessageReader.java:182)
	at com.genymobile.scrcpy.ControlMessageReader.next(ControlMessageReader.java:78)
	at com.genymobile.scrcpy.DesktopConnection.receiveControlMessage(DesktopConnection.java:110)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:82)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$3.run(Server.java:125)
	at java.lang.Thread.run(Thread.java:929)

oppo ace2（系统版本安卓11）报错
AdbProcess::out:[server] ERROR: Exception on thread Thread[Thread-2,5,main]

AdbProcess::out:

AdbProcess::error:java.lang.IllegalArgumentException: Bad position -65522/30
	at java.nio.Buffer.position(Buffer.java:259)
	at java.nio.ByteBuffer.position(ByteBuffer.java:812)
	at com.genymobile.scrcpy.ControlMessageReader.parseString(ControlMessageReader.java:123)
	at com.genymobile.scrcpy.ControlMessageReader.parseSetClipboard(ControlMessageReader.java:182)
	at com.genymobile.scrcpy.ControlMessageReader.next(ControlMessageReader.java:78)
	at com.genymobile.scrcpy.DesktopConnection.receiveControlMessage(DesktopConnection.java:110)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:82)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$3.run(Server.java:125)
	at java.lang.Thread.run(Thread.java:923)

小米12（系统版本安卓12）报错
AdbProcess::out:[server] ERROR: Exception on thread Thread[Thread-2,5,main]

AdbProcess::error:java.lang.IllegalArgumentException: Bad position -65522/30
	at java.nio.Buffer.position(Buffer.java:259)
	at java.nio.ByteBuffer.position(ByteBuffer.java:812)
	at com.genymobile.scrcpy.ControlMessageReader.parseString(ControlMessageReader.java:123)
	at com.genymobile.scrcpy.ControlMessageReader.parseSetClipboard(ControlMessageReader.java:182)
	at com.genymobile.scrcpy.ControlMessageReader.next(ControlMessageReader.java:78)
	at com.genymobile.scrcpy.DesktopConnection.receiveControlMessage(DesktopConnection.java:110)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:82)
	at com.genymobile.scrcpy.Controller.control(Controller.java:73)
	at com.genymobile.scrcpy.Server$3.run(Server.java:125)
	at java.lang.Thread.run(Thread.java:920)

**Comment by asd0925** [comment]
还有个问题 投屏的时候，华为和小米输入密码时会黑屏，oppo则不会，请问哪里设置能改成不黑屏

**Comment by barry-ran** [comment]
看报错是x传的不对

**Comment by asd0925** [comment]
> 

请问x传不对是啥意思，不太懂

**Comment by asd0925** [comment]
> 看报错是x传的不对

请问x传不对是啥意思，不太懂

**Comment by barry-ran** [comment]
我看下代码分析下吧
