### ISSUE TITLE
Error on v2.1.0 release

### ISSUE THREAD

**Issue by chromer030** [barry-ran/QtScrcpy#697]
```
start server...
AdbProcessImpl::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcessImpl::error:java.lang.IllegalArgumentException: The server version (1.24) does not match the client (1.21)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:167)
	at com.genymobile.scrcpy.Server.main(Server.java:331)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(Unknown Source)
```

Android 7.1.2 arm64
Arch Linux

**Comment by Broukmiken** [comment]
Same error : force close

AdbProcessImpl::error:stack corruption detected (-fstack-protector)

And where is the record button please ?
i don't know how to record the screen in mkv or mp4 even if i have set the record directory.
thanks.

**Comment by barry-ran** [comment]
2.1.1 fixed
