### ISSUE TITLE
Android version 12

### ISSUE THREAD

**Issue by 786ironman** [barry-ran/QtScrcpy#705]
Hey, I have android phone with android version 12 and i think it does not work on that

**Comment by 786ironman** [comment]
hey @barry-ran does the software work on android 12 because i have android phone mi 11 it does not work on it but it works on my other phone with android 10

**Comment by barry-ran** [comment]
error log?

**Comment by 786ironman** [comment]
There was no error message but when i connected my smart phone it just
didn't show up , i had different phone with android 10 which worked

**Comment by RaptorX** [comment]
I tried with an older version of QtScrCpy and got this error:

```
AdbProcess::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcess::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.setDisplaySurface(ScreenEncoder.java:178)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:70)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:34)
	at com.genymobile.scrcpy.Server.main(Server.java:163)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplaySurface(SurfaceControl.java:73)
	... 6 more
Caused by: java.lang.IllegalArgumentException: displayToken must not be null
	at android.view.SurfaceControl$Transaction.setDisplaySurface(SurfaceControl.java:3145)
	at android.view.SurfaceControl.setDisplaySurface(SurfaceControl.java:2214)
	... 8 more

```
Also tested with ScrCpy and it connects correctly on the same device.
So whatever the problem is, you can find the answer on the other project :)
