### ISSUE TITLE
是否有办法关掉投屏功能, 仅使用按键和触控映射功能?

### ISSUE THREAD

**Issue by ayasa520** [barry-ran/QtScrcpy#716]
最新版 Waydroid 的 `screenrecord` 不可用
```
waydroid:/ $ screenrecord /sdcard/file.mp4
Encoder failed (err=-38)
```
这导致在qtscrcpy启动服务时会报错
```
start server...
AdbProcessImpl::out:/opt/qtscrcpy/scrcpy-server: 1 file pushed, 0 skipped. 78.7 MB/s (41159 bytes in 0.000s)

AdbProcessImpl::out:[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 11)

server start finish in 0.275s

"[FFmpeg] Warning: not compiled with thread support, using thread emulation\n"

AdbProcessImpl::out:[server] DEBUG: Using encoder: 'OMX.google.h264.encoder'

update devices...
adb run
AdbProcessImpl::out:List of devices attached
192.168.240.112:5555	device

AdbProcessImpl::out:[server] ERROR: Encoding error: java.lang.IllegalStateException: null

AdbProcessImpl::out:[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcessImpl::error:java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
``

但是 `adb shell input tap x y ` 这类指令还是能用的. 所以我想有没有办法让 qtscrcpy 不从 android 中获取图像, 而以透明的方式盖在 waydroid 窗口上, 同时保留按键和触控映射

**Comment by barry-ran** [comment]
目前没有
