### ISSUE TITLE
小米 11 Ultra 升级到 Android 13 后连接成功只能查看不能操控

### ISSUE THREAD

**Issue by DustinWin** [barry-ran/QtScrcpy#745]
QtScrcpy 版本：v2.1.2
机型：小米 11 Ultra
系统：MIUI14（Android 13）
问题：成功连接有线或无线后，通过 QtScrcpy 只能查看手机屏幕，但无法操控手机屏幕
当通过有线连接时，鼠标点击手机屏幕区域报错，内容如下：
```"pos": {"x": 0.826558, "y": 0.361314}

AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)

AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
```
当通过 WiFi 连接时，鼠标点击手机屏幕区域报错，内容如下：
```"pos": {"x": 0.829268, "y": 0.360097}

AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)

AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
```
另外安装 sndcpy 也失败，且无法“开始音频”，报错如下：
```"AudioOutput::" "Begin Runing...\r\n"

"AudioOutput::" "Waiting for device 93e54cf8...\r\n"

"AudioOutput::" "Find device 93e54cf8\r\n"

"AudioOutput::" "Install sndcpy.apk... \r\n"

"AudioOutput::" "Failure [DELETE_FAILED_INTERNAL_ERROR]\r\n"

"AudioOutput::" "uninstall failed\r\n"

"AudioOutput::" "adb: failed to install sndcpy.apk: \r\nException occurred while executing 'install':\r\njava.lang.Sec"

"AudioOutput::" "urityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMI"

"AudioOutput::" "SSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag\r\n\tat com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:791)\r\n\tat com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:615)\r\n\tat com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC"

"AudioOutput::" "Performing Streamed Install\r\n"

"AudioOutput::" "Failed with error #1.\r\n"```

**Comment by DustinWin** [comment]
已经解决，https://github.com/appium/appium/issues/13802#issuecomment-587802222

**Comment by KmBase** [comment]
关闭MIUI优化

**Comment by HackerTao** [comment]
启用系统优化项，关闭
![Uploading 微信图片_20240705094416.png…]()

**Comment by HackerTao** [comment]
启用系统优化项，关闭
![微信图片_20240705094416](https://github.com/barry-ran/QtScrcpy/assets/12810544/98515b05-ee5a-474b-a6ba-e81fe04f16f8)

**Comment by zergmk2** [comment]
> 启用系统优化项，关闭 ![微信图片_20240705094416](https://private-user-images.githubusercontent.com/12810544/345977631-98515b05-ee5a-474b-a6ba-e81fe04f16f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzMyNDIsIm5iZiI6MTczMTU3Mjk0MiwicGF0aCI6Ii8xMjgxMDU0NC8zNDU5Nzc2MzEtOTg1MTViMDUtZWU1YS00NzRiLWE2YmEtZTgxZmUwNGYxNmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZTgxM2RmOTM2YjVkNGY3MzgxMzNlMzA3ZTRjNDA5M2U5NDdjYTM1YjdmZmViZDY3NDhjZGZmZjFiNWRlNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XnguVF6Wch4-4SvCYEIWp7MXH58cWsWso6LcvLZn1R4)

测试有效
