### ISSUE TITLE
小米  红米 redmi k50 ultra (至尊版) 连接后无法操控！

### ISSUE THREAD

**Issue by MrTiany** [barry-ran/QtScrcpy#766]
OS：MIUI 14.0.5 
Android：13
滑动或按键控制台报错：
`AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:206)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:210)
	at com.genymobile.scrcpy.Controller.injectKeycode(Controller.java:148)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:88)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)

AdbProcessImpl::error:at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:916)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)

AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:206)
	at com.genymobile.scrcpy.Device.injectKeyEvent(Device.java:210)
	at com.genymobile.scrcpy.Controller.injectKeycode(Controller.java:148)

AdbProcessImpl::error:at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:88)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 10 more``

**Comment by MrTiany** [comment]
@barry-ran 求帮助！

**Comment by DustinWin** [comment]
参考这个 https://github.com/barry-ran/QtScrcpy/issues/745#issuecomment-1407711843

**Comment by MrTiany** [comment]
> 参考这个 [#745 (comment)](https://github.com/barry-ran/QtScrcpy/issues/745#issuecomment-1407711843)

十分感谢！！！已解决

**Comment by shenqimolisha** [comment]
> 参考这个 https://github.com/barry-ran/QtScrcpy/issues/745#issuecomment-1407711843

这个议题也没说怎么解决啊，你们怎么处理的？我点击启动adbd，手机就弹出来三个框 仅充电 传输文件 传输照片。点了哪个都没反应啊。安装sndcpy也是错误代码，什么鬼

**Comment by FYpanda** [comment]
> > 参考这个 [#745 (comment)](https://github.com/barry-ran/QtScrcpy/issues/745#issuecomment-1407711843)
> 
> 这个议题也没说怎么解决啊，你们怎么处理的？我点击启动adbd，手机就弹出来三个框 仅充电 传输文件 传输照片。点了哪个都没反应啊。安装sndcpy也是错误代码，什么鬼

如果使用的是MIUI类型的操作系统，请启用USB调试（安全设置）并重新启动手机
