### ISSUE TITLE
redmi note12 turbo，可以显示画面，不能操作，已经开启USB调试（安全设置）

### ISSUE THREAD

**Issue by Grivia** [barry-ran/QtScrcpy#832]
日志：
"pos": {"x": 0.455587, "y": 0.379845}

AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)

AdbProcessImpl::error:Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:912)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:617)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)

java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:35)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1294)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1153)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:1182)
	... 9 more

AdbProcessImpl::out:[server] ERROR: Could not invoke method
[server] ERROR: Could not invoke method

**Comment by alex-loding** [comment]
调试下面有个USB调试(安全设置) 打开这个才能允许触摸操作。

**Comment by Xie-Long-0** [comment]
在开发者选项最后面把启用MIUI优化关掉再连接就可以了，连上后可以把该选项再打开，不然界面会很丑
