### ISSUE TITLE
Encoding error: java.lang.IllegalStateException: null  

### ISSUE THREAD

**Issue by cool-delete** [barry-ran/QtScrcpy#847]
When connected via WiFi, the display of continuous motion in the animation will exhibit blocking behavior.

![卡顿](https://github.com/barry-ran/QtScrcpy/assets/13638610/3e153a70-a4a8-4711-a5be-5e8f8eb668b5)

<details><summary>code</summary>
<p>

```
AdbProcessImpl::out:[server] ERROR: Encoding error: java.lang.IllegalStateException: null

AdbProcessImpl::out:[server] ERROR: Exception on thread Thread[main,5,main]

AdbProcessImpl::error:java.lang.IllegalStateException
	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
	at android.media.MediaCodec.releaseOutputBufferInternal(MediaCodec.java:3689)
	at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:3610)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:174)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
```

</p>
</details>

**Comment by cool-delete** [comment]
![卡顿](https://github.com/barry-ran/QtScrcpy/assets/13638610/4326d2f9-6b26-4642-9125-b16a738e3227)
This is a screenshot under normal conditions.

**Comment by cool-delete** [comment]
It seems to be an issue with adb.exe. After ending the adb process and reconnecting to WiFi, the display no longer gets blocked. Although the problem recurs over time.

**Comment by cool-delete** [comment]
It seems to be an issue with adb.exe. After ending the adb process and reconnecting the device via WiFi, the display is no longer blocked. Although over time, the problem recurs.

**Comment by cool-delete** [comment]
gpt告诉我不要设置太低的码率 否者画面会出现处理不过来的情况 就会发生类似这样的卡顿 我改为2Mbps后好了很多 感谢gpt👍
