### ISSUE TITLE
start qtscrcpy faild for android 14

### ISSUE THREAD

**Issue by geebadan** [barry-ran/QtScrcpy#848]
**start exception**
AdbProcessImpl::out:[server] ERROR: Could not invoke method

AdbProcessImpl::error:java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:103)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)

**operation phone**
dbProcessImpl::out:[server] ERROR: Exception on thread Thread[Thread-2,5,main]

AdbProcessImpl::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:271)

AdbProcessImpl::error:... 9 more

**Comment by mkh66346263** [comment]
https://github.com/barry-ran/QtScrcpy/issues/907
