### ISSUE TITLE
小米13 android 14正常连接，无法操作

### ISSUE THREAD

**Issue by lisnn** [barry-ran/QtScrcpy#865]
小米13，miui14.0.3，android 14 ，开启了usb调试（安全设置）。能正常连接上，但是不能操作，日志也是只输出了下面这些，没有报错

update devices...
adb run
AdbProcessImpl::out:List of devices attached
192.168.1.37:5555	device

"pos": {"x": 0.823034, "y": 0.416244}

"pos": {"x": 0.856742, "y": 0.439086}

"pos": {"x": 0.856742, "y": 0.439086}

"pos": {"x": 0.856742, "y": 0.439086}

update devices...
adb run
AdbProcessImpl::out:List of devices attached
192.168.1.37:5555	device

**Comment by xye888** [comment]
USB调试模式下面还有一个USB调试模式（安全模式）  要打开

**Comment by lisnn** [comment]
> USB调试模式下面还有一个USB调试模式（安全模式） 要打开

打开了，没用

**Comment by FourteenDP** [comment]
小米11 ultra 安卓13 MIUI 14.0.11 同问题

**Comment by viarotel** [comment]
可以尝试一下最新的[escrcpy](https://github.com/viarotel-org/escrcpy) 支持多设备管理 具有深色模式 支持单个设备独立配置等 
高级功能

**Comment by android-1995** [comment]
小米13 android 14 同问题+1

**Comment by BingQianceng** [comment]
pixel 5 android14 同样的问题   求解啊

**Comment by ooil929** [comment]
小米10安卓14 一样无法控制

**Comment by zuohx** [comment]
> 可以尝试一下最新的[escrcpy](https://github.com/viarotel-org/escrcpy) 支持多设备管理 具有深色模式 支持单个设备独立配置等 高级功能

可惜他不支持windows平台

**Comment by 2-3-5-7** [comment]
直接用 https://github.com/Genymobile/scrcpy 吧，android 14 正常

**Comment by yuanyihan** [comment]
你需要关闭【启动miui优化】，也在开发者选项，在下面

**Comment by riginnnn** [comment]
> 你需要关闭【启动miui优化】，也在开发者选项，在下面

不行

**Comment by General110** [comment]
> 持多设备管理 具有深色模式 支持单个设备独立配置等

刚试了下 最新版极限投屏可以 点击滑动

**Comment by cuijianzhi** [comment]
> > 你需要关闭【启动miui优化】，也在开发者选项，在下面
> 
> 不行

Mi 11这个打开可以操作了

**Comment by zzhangpurdue** [comment]
> 你需要关闭【启动miui优化】，也在开发者选项，在下面

我试了关闭一个叫启动系统优化就可以了，不过手机界面会瞬间变的奇丑

**Comment by e9ab98e991ab** [comment]
AdbProcessImpl::out:[server] DEBUG: Using encoder: 'OMX.qcom.video.encoder.avc'

update devices...
adb run
AdbProcessImpl::out:List of devices attached
c601f035	device

"pos": {"x": 0.0968523, "y": 0.0670391}

AdbProcessImpl::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException

AdbProcessImpl::out:[server] ERROR: Exception on thread Thread[Thread-2,5,main]

AdbProcessImpl::error:at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:274)
	... 9 more
	错误日志

**Comment by showyourlucky** [comment]
很奇怪, 第一次连接是可以控制的, 后面不知道为什么就控制不了了

**Comment by flamingsun** [comment]
我的手机为小米14pro，打开USB调试后，有一个 ”默认USB配置“，选择 MIDI即可。
