### ISSUE TITLE
小米13连接上后，只能看，无法控制

### ISSUE THREAD

**Issue by kzh521** [barry-ran/QtScrcpy#873]
update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
192.168.5.18:5555	device
emulator-5556	offline

start server...
AdbProcessImpl::out:D:/QtScrcpy-win-x64-v2.1.1/scrcpy-server: 1 file pushed, 0 skipped. 65.6 MB/s (41159 bytes in 0.001s)

AdbProcessImpl::out:[server] INFO: Device: Xiaomi 2211133C (Android 14)

server start finish in 0.602s

AdbProcessImpl::out:[server] ERROR: Could not invoke method
[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'

AdbProcessImpl::error:java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:103)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:368)

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
192.168.5.18:5555	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
192.168.5.18:5555	device
emulator-5556	offline

**Comment by kechuan** [comment]
看看你的开发者选项里的 USB调试(安全设置)有没有打开
下面的功能介绍里有这样一段话:允许透过usb调试修改权限或模拟点击

无论是scrcpy还是这个都会需要这个东西来点击操作的

**Comment by kzh521** [comment]
开usb调试了
![2728336d74be43e343be2cc2e9a3f15](https://github.com/barry-ran/QtScrcpy/assets/43432452/32b55274-21b5-4366-b998-9860edecb7f2)

**Comment by kzh521** [comment]
还是没有作用

**Comment by kzh521** [comment]
update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

start server...
AdbProcessImpl::out:D:/QtScrcpy-win-x64-v2.1.1/scrcpy-server: 1 file pushed, 0 skipped. 56.3 MB/s (41159 bytes in 0.001s)

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

AdbProcessImpl::out:[server] INFO: Device: Xiaomi 2211133C (Android 14)

AdbProcessImpl::out:[server] ERROR: Could not invoke method

server start finish in 0.556s

AdbProcessImpl::error:java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.addPrimaryClipChangedListener [interface android.content.IOnPrimaryClipChangedListener, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.getAddPrimaryClipChangedListener(ClipboardManager.java:103)
	at com.genymobile.scrcpy.wrappers.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:111)
	at com.genymobile.scrcpy.Device.<init>(Device.java:103)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:368)

AdbProcessImpl::out:[server] DEBUG: Using encoder: 'c2.qti.avc.encoder'

"pos": {"x": 0.555556, "y": 0.563095}

AdbProcessImpl::out:[server] ERROR: Exception on thread Thread[Thread-2,5,main]

AdbProcessImpl::error:java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:65)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:195)
	at com.genymobile.scrcpy.Device.injectEvent(Device.java:199)
	at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:223)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:98)
	at com.genymobile.scrcpy.Controller.control(Controller.java:75)
	at com.genymobile.scrcpy.Server$3.run(Server.java:133)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.genymobile.scrcpy.wrappers.ServiceManager.getInputManager(ServiceManager.java:62)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:207)
	at android.hardware.input.InputManager.getInstance(InputManager.java:271)
	... 9 more

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

update devices...
adb run
AdbProcessImpl::out:List of devices attached
319e3385	device
emulator-5556	offline

**Comment by kechuan** [comment]
那。。不好意思 我也不知道了
我是发现这东西对安卓版本越高就越难用

以前我的安卓10的旧机 开了就能用

到后面我的安卓13需要root调那个安全中心的配置文件才能用。。
依据这个方法: https://zhuanlan.zhihu.com/p/603628922

![image](https://github.com/barry-ran/QtScrcpy/assets/42696536/85ec188c-68cf-4f2d-8964-45e3d33b29f7)

**Comment by unsunzhensheng** [comment]
按照您知乎给的方法，我还是不行
设备：13Pro
版本：MIUI14.0.4
请问还有其他解决方案吗

**Comment by 00helloworld11** [comment]
兄弟我开始跟你一样的问题,重启一下手机就好了 

> 开usb调试了 ![2728336d74be43e343be2cc2e9a3f15](https://private-user-images.githubusercontent.com/43432452/283290621-32b55274-21b5-4366-b998-9860edecb7f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5ODk4MzMsIm5iZiI6MTcwMDk4OTUzMywicGF0aCI6Ii80MzQzMjQ1Mi8yODMyOTA2MjEtMzJiNTUyNzQtMjFiNS00MzY2LWI5OTgtOTg2MGVkZWNiN2YyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDA5MDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMDBhM2UwYzM0MDkyNDk1YzIwYTlhOTYzYjc5YzA0OWM5ZDU4OWM0ODYwMWZlYzYyMDJlZjYwYWUzYmY1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RJWenFGoAvwROsWeO_l-5abJdTk-TG6qdETCPCihApE)

**Comment by controlledentropy** [comment]
miui14路过，开启上面所有选项重启试试。我也是第一次使用usb和wireless debug都不能操控。后来打开所有调试相关选项，后续重启过机器后偶然尝试一下发现可以正常使用了

**Comment by clovis01** [comment]
小米澎湃OS也是把USB的都打开，重启一下就可以控制了

**Comment by sitboy** [comment]
需要把账号与同步中 谷歌基础服务打开。

**Comment by Jail0910** [comment]
我用ubuntu 开权限就能用了
sudo scrcpy

**Comment by kyle927** [comment]
只重啟無用
开启 USB调试（安全设置）後，就算沒重啟，重新連qtscrcpy就可用
分享~thx~
