### ISSUE TITLE
安卓14 k60u +最新2.2.0版本

### ISSUE THREAD

**Issue by Xiepoder** [barry-ran/QtScrcpy#926]
点击那个眼睛 关闭屏幕 或者 ctrl+o 都关闭不了屏幕

AdbProcessImpl::error:[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

**Comment by liuqingdada** [comment]
这个库应该没人维护了
readme中描述：QtScrcpy is based on Genymobile's scrcpy project.
可以使用这个库

**Comment by Xiepoder** [comment]
> 这个库应该没人维护了 readme中描述：QtScrcpy is based on Genymobile's scrcpy project. 可以使用这个库

嗯啊 可以了   -S -w --shortcut-mod=lctrl --power-off-on-close
加了点 参数 话说要是能自己编译的话 用scrcpy 2.2+应该就能解决了

**Comment by barry-ran** [comment]
[v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1) fixed
