### ISSUE TITLE
Cannot turnoff screen Android 14

### ISSUE THREAD

**Issue by lehunghup** [barry-ran/QtScrcpy#927]
"ERROR: Could not get physical display ids"
This error appears after i update my pixel 6a to android 14.
Please help

**Comment by lehunghup** [comment]
AdbProcessImpl::error:[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

**Comment by barry-ran** [comment]
try [v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1) fixed

**Comment by lehunghup** [comment]
> try [v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1)

it works. thank you

**Comment by lehunghup** [comment]
> try [v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1)

it works. thank you
