### ISSUE TITLE
Could not invoke method

### ISSUE THREAD

**Issue by LeeSaltyFish** [barry-ran/QtScrcpy#937]
当我使用息屏功能的时候/自动息屏功能的时候，会报错如下

AdbProcessImpl::error:[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

**Comment by LeeSaltyFish** [comment]
OK I find the solution

download the scrcpy-server

copy and cover the scrcpy-server in the folder

change the config.ini in config folder

the change detail is “ServerVersion=2.1.1” to "ServerVersion=2.4"

**Comment by barry-ran** [comment]
try [v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1)

**Comment by zslhub** [comment]
> 试用 [v2.2.1](https://github.com/barry-ran/QtScrcpy/releases/tag/v2.2.1)

刚刚尝试了最新版本2.2.1，问题还是存在的，报错如下：
AdbProcessImpl::error:Native registration unable to find class 'com/android/server/DeviceControlService'; aborting...
AdbProcessImpl::error:Aborted
