### ISSUE TITLE
【老手机】荣耀v10无法使用，报错

### ISSUE THREAD

**Issue by pzistart** [barry-ran/QtScrcpy#965]
AdbProcessImpl::out:[server] INFO: Device: [HUAWEI] HONOR BKL-AL20 (Android 10)

readInfo timeout

AdbProcessImpl::out:[server] DEBUG: Using video encoder: 'OMX.hisi.video.encoder.avc'
[server] INFO: Retrying with -m1920...
[server] INFO: Retrying...
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] INFO: Retrying with -m1024...
[server] INFO: Retrying...
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped

AdbProcessImpl::error:[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Encoding error: java.lang.IllegalArgumentException: null
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2023)
	at android.media.MediaCodec.configure(MediaCodec.java:1951)
	at com.genymobile.scrcpy.SurfaceEncoder.streamScreen(SurfaceEncoder.java:69)
	at com.genymobile.scrcpy.SurfaceEncoder.lambda$start$0$com-genymobile-scrcpy-SurfaceEncoder(SurfaceEncoder.java:253)
	at com.genymobile.scrcpy.SurfaceEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:929)

update devices...

**Comment by pzistart** [comment]
一样 我的是荣耀v20 
你的解决了吗 楼主

**Comment by yuan4561** [comment]
我用的华为matepad paper使用QtScrcpy也是一样报上面的错误无法连接。
后来我直接用Scrcpy修改视频编码器，就可以投屏了。

设备上可能有多个编码器。它们可以按以下方式列出：
scrcpy --list-encoders
修改编码模式连接成功
scrcpy --video-codec=h264 --video-encoder='OMX.google.h264.encoder'

**Comment by pzistart** [comment]
> 我用的华为matepad paper使用QtScrcpy也是一样报上面的错误无法连接。 后来我直接用Scrcpy修改视频编码器，就可以投屏了。
> 
> 设备上可能有多个编码器。它们可以按以下方式列出： scrcpy --list-encoders 修改编码模式连接成功 scrcpy --video-codec=h264 --video-encoder='OMX.google.h264.encoder'

大佬，能详细点吗，我荣耀V10应该咋整，按照你说的执行这个命令他这么提示了

![Image](https://github.com/user-attachments/assets/ecf76bf7-0329-42aa-a55a-83ed0bb62b57)
