### ISSUE TITLE
手机预装Android15 时，展示小弹框，无法操作，如下图

### ISSUE THREAD

**Issue by yanghuizhi** [barry-ran/QtScrcpy#993]
![image](https://github.com/barry-ran/QtScrcpy/assets/29268369/53d277d6-a1bc-4268-8591-ac660f375df8)

报错如下：

AdbProcessImpl::out:[server] DEBUG: Using video encoder: 'c2.mtk.avc.encoder'
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped

AdbProcessImpl::error:[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:85)
	at com.genymobile.scrcpy.ScreenEncoder.createDisplay(ScreenEncoder.java:272)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:75)
	at com.genymobile.scrcpy.ScreenEncoder.lambda$start$0$com-genymobile-scrcpy-ScreenEncoder(ScreenEncoder.java:294)
	at com.genymobile.scrcpy.ScreenEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.createDisplay [class java.lang.String, boolean]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getMethod(Class.java:2450)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.createDisplay(SurfaceControl.java:83)
	... 5 more

**Comment by yanghuizhi** [comment]
原先使用的是  2.2.0 ，更新成 2.2.1 最新之后，问题解决！
