### ISSUE TITLE
小米13，Android14，os版本：1.0.8.0，USB有线连接，使用期间突然闪退

### ISSUE THREAD

**Issue by Fowver** [barry-ran/QtScrcpy#999]
AdbProcessImpl::out:D:/Downloads/QtScrcpy-win-x64-v2.2.0/scrcpy-server: 1 file pushed, 0 skipped. 133.4 MB/s (56995 bytes in 0.000s)

AdbProcessImpl::out:27183

AdbProcessImpl::out:[server] INFO: Device: [Xiaomi] Xiaomi 2211133C (Android 14)

server start finish in 0.447s

AdbProcessImpl::out:[server] DEBUG: Using video encoder: 'c2.qti.avc.encoder'

AdbProcessImpl::error:[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.view.SurfaceControl.getPhysicalDisplayIds []
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getGetPhysicalDisplayIdsMethod(SurfaceControl.java:137)
	at com.genymobile.scrcpy.wrappers.SurfaceControl.getPhysicalDisplayIds(SurfaceControl.java:144)
	at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:319)
	at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:169)
	at com.genymobile.scrcpy.Controller.control(Controller.java:83)
	at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:91)
	at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:1012)
[server] ERROR: Could not get physical display ids

update devices...
adb run
AdbProcessImpl::out:List of devices attached
21bbbc64	device

update devices...
adb run
AdbProcessImpl::out:List of devices attached
21bbbc64	device

**Comment by Fowver** [comment]
这个我发现是因为数据线没有插到USB3.0插口（蓝色的插口），插回USB3.0插口后就正常不会闪退了
